planning:
    resource: "@PlanningBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
fos_user_resseting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

