planning_location:
    resource: "@PlanningBundle/Resources/config/routing_location.yml"
    prefix: /admin/location

planning_teacher:
    resource: "@PlanningBundle/Resources/config/routing_teacher.yml"
    prefix: /admin/teacher

planning_student:
    resource: "@PlanningBundle/Resources/config/routing_student.yml"
    prefix: /admin/student

planning_admin:
    resource: "@PlanningBundle/Resources/config/routing_admin.yml"
    prefix: /admin

planning_schedule:
    resource: "@PlanningBundle/Resources/config/routing_schedule.yml"
    prefix: /manage/schedule

planning:
    resource: "@PlanningBundle/Resources/config/routing_public.yml"
    prefix: /