student_promo_list:
    path:     /
    defaults: { _controller: PlanningBundle:Student:index }

add_student:
    path:  /student/new
    defaults : { _controller: PlanningBundle:Student:addStudent }

student_list:
    path : /students/{offset}
    defaults : { _controller: PlanningBundle:Student:studentList, offset: 0 }
    requirements:
         offset: \d+

show_student:
    path: /student/{id}
    defaults: {_controller: PlanningBundle:Student:showStudent}

edit_student:
    path: /student/{id}/edit
    defaults : {_controller: PlanningBundle:Student:editStudent}

delete_student:
    path: /promo/remove/{id}
    defaults : {_controller: PlanningBundle:Student:removeStudentFromPromo}

add_promo:
    path: /promo/new
    defaults : {_controller: PlanningBundle:Student:addPromo}

edit_promo:
    path: /promo/{id}/edit
    defaults : {_controller: PlanningBundle:Student:editPromo}

show_promo:
    path: /promo/{id}
    defaults : {_controller: PlanningBundle:Student:showPromo}

